models/User.php
<?php

namespace app\models;

use Faker\Provider\DateTime;
use phpDocumentor\Reflection\DocBlock\Tags\Reference\Url;
use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property int $personal_code
 * @property int $phone
 * @property bool $active
 * @property bool $dead
 * @property string $lang
 *
 * @property Loan[] $loans
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'personal_code', 'phone'], 'required'],
            [['first_name', 'last_name', 'email', 'lang'], 'string'],
            [['personal_code', 'phone'], 'default', 'value' => null],
            ['personal_code', 'string', 'length' => 11],
            [['personal_code', 'phone'], 'integer'],
            //['email', 'email'],
            [['active', 'dead'], 'boolean'],
        ];
    }

    public function getNameSurname()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'email' => 'Email',
            'personal_code' => 'Personal Code',
            'phone' => 'Phone',
            'active' => 'Active',
            'dead' => 'Dead',
            'lang' => 'Lang',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoans()
    {
        return $this->hasMany(Loan::className(), ['user_id' => 'id']);
    }

    public function getApplyPermission()
    {
        if ($this->getAge() >= 18)
        {
            return true;
        }

        return false;
    }

    public function getAge()
    {
       return self::calculateAge($this->personal_code);
    }

    public static function calculateAge($personal_code)
    {
        switch (substr($personal_code, 0, 1))
        {
            case 1:
            case 2:
                $x = 18;
                break;
            case 3:
            case 4:
                $x = 19;
                break;
            case 5:
            case 6:
                $x = 20;
                break;
        }
        $year = substr($personal_code, 1, 2);
        $month = substr($personal_code, 3, 2);
        $day = substr($personal_code, 5, 2);

        $birth_day = new \DateTime("$x$year-$month-$day");
        $diff = $birth_day->diff(new \DateTime("today"));

        return $diff->y;
    }
}

controllers/LoanController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use app\models\Loan;
use app\models\LoanSearch;
use yii\data\Pagination;
use yii\data\Sort;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LoanController implements the CRUD actions for Loan model.
 */
class LoanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LoanSearch();
        $sort = new Sort([
            'attributes' => [
                'id',
                'first_name',
                'last_name',
                'amount',
                'interest',
                'duration',
                'start_date',
                'end_date'
            ],
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $countQuery = clone $dataProvider->query;

        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $pages->defaultPageSize = 25;

        $loans = $dataProvider->query->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy($sort->orders)
            ->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'loans' => $loans,
            'pages' => $pages,
            'sort' => $sort
        ]);
    }

    /**
     * Displays a single Loan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Loan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Loan();
        $users = User::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'users' => ArrayHelper::map($users, 'id', 'nameSurname')
        ]);
    }

    /**
     * Updates an existing Loan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $users = User::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'users' => ArrayHelper::map($users, 'id', 'nameSurname')
        ]);
    }

    /**
     * Deletes an existing Loan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Loan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Loan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Loan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\Loan;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\data\Pagination;
use yii\data\Sort;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $sort = new Sort([
            'attributes' => [
                'id',
                'first_name',
                'last_name',
                'personal_code',
                'phone',
                'email',
                'lang'
            ],
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $countQuery = clone $dataProvider->query;

        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $pages->defaultPageSize = 25;

        $users = $dataProvider->query->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy($sort->orders)
            ->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'users' => $users,
            'pages' => $pages,
            'sort' => $sort
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $user = $this->findModel($id);

        if ($user->getAge() >= 18)
        {
            Yii::$app->session->setFlash('success', 'User is allowed to apply for a loan.');
        }
        else {
            Yii::$app->session->setFlash('error', 'User is not allowed to apply for a loan!');
        }
        return $this->render('view', [
            'model' => $user,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $loans = Loan::findAll(['user_id' => $id]);
        if ($loans != null)
        {
            Yii::$app->session->setFlash('error', 'You cannot delete a user with loans! Delete loans first.');
            return $this->redirect(['view', 'id' => $id]);
        }
        else
        {
            $this->findModel($id)->delete();
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false,
    ]); ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>

    <?= $form->field($model, 'email')
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'email',
                'removeMaskOnSubmit' => true,
            ]
        ]);
    ?>

    <?= $form->field($model, 'personal_code')
        ->widget(MaskedInput::classname(), [
            'mask' => '99999999999',
            'clientOptions' => [
                'removeMaskOnSubmit' => true,
            ]
        ]);
    ?>

    <?= $form->field($model, 'phone')
        ->widget(MaskedInput::classname(), [
            'mask' => '(999) 999 99 99',
            'clientOptions' => [
                'removeMaskOnSubmit' => true,
            ]
        ]);
    ?>

    <?= $form->field($model, 'active')->checkbox() ?>

    <?= $form->field($model, 'dead')->checkbox() ?>

    <?= $form->field($model, 'lang') ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'enableClientValidation' => false,
    ]); ?>

    <?= $form->field($model, 'personal_code')
        ->widget(MaskedInput::classname(), [
            'mask' => '99999999999',
            'clientOptions' => [
                'removeMaskOnSubmit' => true,
            ]
        ]);
    ?>
    <div class="row">
        <div class="col-sm-4">
            <?= $form->field($model, 'id')
                ->widget(MaskedInput::classname(), [
                    'clientOptions' => [
                        'alias' =>  'integer',
                    ],
                ]);
            ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'first_name') ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'last_name') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'phone')
                ->widget(MaskedInput::classname(), [
                    'mask' => '(999) 999 99 99',
                    'clientOptions' => [
                        'removeMaskOnSubmit' => true,
                    ]
                ]);
            ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($model, 'email') ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\widgets\LinkPager;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::button('Filter Users',
            ['class' => 'btn btn-warning', 'data-toggle' => 'modal', 'data-target' => '#user-filter-modal']) ?>
    </p>

    <table class="table">
        <thead>
        <tr>
            <th><?= $sort->link('id') ?></th>
            <th><?= $sort->link('first_name') ?></th>
            <th><?= $sort->link('last_name') ?></th>
            <th><?= $sort->link('personal_code') ?></th>
            <th><?= $sort->link('phone') ?></th>
            <th><?= $sort->link('email') ?></th>
            <th><?= $sort->link('lang') ?></th>
            <th>View</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($users as $user): ?>
        <tr>
            <td><?= $user->id ?></td>
            <td><?= $user->first_name ?></td>
            <td><?= $user->last_name ?></td>
            <td><?= $user->personal_code ?></td>
            <td><?= $user->phone ?></td>
            <td><?= $user->email ?></td>
            <td><?= $user->lang ?></td>
            <td><a href="<?= Url::to(['user/view', 'id' => $user->id]) ?>" class="btn btn-sm btn-primary">Details</a></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?= LinkPager::widget(['pagination' => $pages]); ?>
</div>

<div id="user-filter-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Filter Users</h4>
            </div>
            <div class="modal-body">
                <?= $this->render('_search', ['model' => $searchModel]); ?>
            </div>
        </div>

    </div>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->first_name . ' ' . $model->last_name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('User\'s Loans', Url::to(['loan/index', 'LoanSearch[user_id]' => $model->id]), ['class' => 'btn btn-success']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'first_name:ntext',
            'last_name:ntext',
            'email:ntext',
            'personal_code',
            'age',
            'phone',
            'active:boolean',
            'dead:boolean',
            'lang:ntext'
        ],
    ]) ?>

</div>