models/Loan.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "loan".
 *
 * @property int $id
 * @property int $user_id
 * @property string $amount
 * @property string $interest
 * @property int $duration
 * @property string $start_date
 * @property string $end_date
 * @property int $campaign
 * @property bool $status
 * @property string $first_name
 * @property string $last_name
 *
 * @property User $user
 */
class Loan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'loan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'amount', 'interest', 'duration', 'start_date', 'end_date', 'campaign'], 'required'],
            [['user_id', 'duration', 'campaign'], 'default', 'value' => null],
            [['user_id', 'duration', 'campaign', 'status'], 'integer'],
            [['amount', 'interest'], 'number'],
            [['start_date', 'end_date'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'amount' => 'Amount',
            'interest' => 'Interest',
            'duration' => 'Duration',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'campaign' => 'Campaign',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

controllers/LoanController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use app\models\Loan;
use app\models\LoanSearch;
use yii\data\Pagination;
use yii\data\Sort;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LoanController implements the CRUD actions for Loan model.
 */
class LoanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Loan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LoanSearch();
        $sort = new Sort([
            'attributes' => [
                'id',
                'first_name',
                'last_name',
                'amount',
                'interest',
                'duration',
                'start_date',
                'end_date'
            ],
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $countQuery = clone $dataProvider->query;

        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $pages->defaultPageSize = 25;

        $loans = $dataProvider->query->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy($sort->orders)
            ->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'loans' => $loans,
            'pages' => $pages,
            'sort' => $sort
        ]);
    }

    /**
     * Displays a single Loan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Loan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Loan();
        $users = User::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'users' => ArrayHelper::map($users, 'id', 'nameSurname')
        ]);
    }

    /**
     * Updates an existing Loan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $users = User::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'users' => ArrayHelper::map($users, 'id', 'nameSurname')
        ]);
    }

    /**
     * Deletes an existing Loan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Loan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Loan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Loan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\Loan;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\data\Pagination;
use yii\data\Sort;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $sort = new Sort([
            'attributes' => [
                'id',
                'first_name',
                'last_name',
                'personal_code',
                'phone',
                'email',
                'lang'
            ],
        ]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $countQuery = clone $dataProvider->query;

        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $pages->defaultPageSize = 25;

        $users = $dataProvider->query->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy($sort->orders)
            ->all();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'users' => $users,
            'pages' => $pages,
            'sort' => $sort
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $user = $this->findModel($id);

        if ($user->getAge() >= 18)
        {
            Yii::$app->session->setFlash('success', 'User is allowed to apply for a loan.');
        }
        else {
            Yii::$app->session->setFlash('error', 'User is not allowed to apply for a loan!');
        }
        return $this->render('view', [
            'model' => $user,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $loans = Loan::findAll(['user_id' => $id]);
        if ($loans != null)
        {
            Yii::$app->session->setFlash('error', 'You cannot delete a user with loans! Delete loans first.');
            return $this->redirect(['view', 'id' => $id]);
        }
        else
        {
            $this->findModel($id)->delete();
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/loan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */
/* @var $model app\models\Loan */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="loan-form">

    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false,
    ]); ?>

    <?= $form->field($model, 'user_id')->dropDownList($users) ?>

    <?= $form->field($model, 'amount')->textInput()
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'decimal',
                'groupSeparator' => ',',
                'autoGroup' => true,
                'removeMaskOnSubmit' => true,
            ],
        ]);
    ?>

    <?= $form->field($model, 'interest')->textInput()
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'decimal',
            ],
        ]);
    ?>

    <?= $form->field($model, 'duration')->textInput()
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'integer',
            ],
        ]);
    ?>

    <?= $form->field($model, 'start_date')->textInput()
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'yyyy-mm-dd'
            ],
        ]);?>

    <?= $form->field($model, 'end_date')->textInput()
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'yyyy-mm-dd'
            ],
        ]);?>

    <?= $form->field($model, 'campaign')->textInput()
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'integer',
            ],
        ]);
    ?>

    <?= $form->field($model, 'status')
        ->widget(MaskedInput::classname(), [
            'clientOptions' => [
                'alias' =>  'integer',
            ],
        ]);
    ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/loan/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */
/* @var $model app\models\LoanSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="loan-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'enableClientValidation' => false,
    ]); ?>

    <div class="row">
        <div class="col-sm-4">
            <?= $form->field($model, 'user_id')->textInput()
                ->widget(MaskedInput::classname(), [
                    'clientOptions' => [
                        'alias' =>  'integer',
                    ],
                ]);
            ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'first_name') ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'last_name') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <?= $form->field($model, 'amount')
                ->textInput()
                ->widget(MaskedInput::classname(), [
                    'clientOptions' => [
                        'alias' =>  'decimal',
                        'groupSeparator' => ',',
                        'autoGroup' => true,
                        'removeMaskOnSubmit' => true,
                    ],
                ]);
            ;?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'interest')->textInput()
                ->widget(MaskedInput::classname(), [
                    'clientOptions' => [
                        'alias' =>  'decimal',
                    ],
                ]);
            ?>
        </div>
        <div class="col-sm-4">
            <?= $form->field($model, 'duration')->textInput()
                ->widget(MaskedInput::classname(), [
                    'clientOptions' => [
                        'alias' =>  'integer',
                    ],
                ]);
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($model, 'start_date')->textInput()
                ->widget(MaskedInput::classname(), [
                    'clientOptions' => [
                        'alias' =>  'yyyy-mm-dd'
                    ],
                ])
            ;?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($model, 'end_date')->textInput()
                ->widget(MaskedInput::classname(), [
                    'clientOptions' => [
                        'alias' =>  'yyyy-mm-dd'
                    ],
                ])
            ;?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/loan/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Loan */

$this->title = 'Create Loan';
$this->params['breadcrumbs'][] = ['label' => 'Loans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="loan-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'users' => $users
    ]) ?>

</div>

views/loan/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->title = 'Loans';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="loan-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Loan', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::button('Filter Loans',
            ['class' => 'btn btn-warning', 'data-toggle' => 'modal', 'data-target' => '#loan-filter-modal']) ?>
    </p>

    <table class="table">
        <thead>
        <tr>
            <th><?= $sort->link('id') ?></th>
            <th><?= $sort->link('first_name') ?></th>
            <th><?= $sort->link('last_name') ?></th>
            <th><?= $sort->link('amount') ?></th>
            <th><?= $sort->link('interest') ?></th>
            <th><?= $sort->link('duration') ?></th>
            <th><?= $sort->link('start_date') ?></th>
            <th><?= $sort->link('end_date') ?></th>
            <th>View</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($loans as $loan): ?>
        <tr>
            <td><?= $loan->id ?></td>
            <td><?= $loan->user->first_name ?></td>
            <td><?= $loan->user->last_name ?></td>
            <td><?= $loan->amount ?> €</td>
            <td><?= $loan->interest ?> %</td>
            <td><?= $loan->duration ?></td>
            <td><?= $loan->start_date ?></td>
            <td><?= $loan->end_date ?></td>
            <td><a href="<?= Url::to(['loan/view', 'id' => $loan->id]) ?>" class="btn btn-sm btn-primary">Details</a></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?= LinkPager::widget(['pagination' => $pages]); ?>
</div>

<div id="loan-filter-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Filter Loans</h4>
            </div>
            <div class="modal-body">
                <?= $this->render('_search', ['model' => $searchModel]); ?>
            </div>
        </div>

    </div>
</div>

views/loan/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Loan */

$this->title = 'Update Loan: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Loans', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="loan-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'users' => $users
    ]) ?>

</div>

views/loan/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Loan */

$this->title = 'Loan #' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Loans', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="loan-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('View User', Url::to(['user/view', 'id' => $model->user_id]), ['class' => 'btn btn-success']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user.first_name',
            'user.last_name',
            'amount',
            'interest',
            'duration',
            'start_date',
            'end_date',
            'campaign',
            'status',
        ],
    ]) ?>

</div>